name: basic-ml-app
services:
  backend:
    build:
      context: .
      dockerfile: app/app.Dockerfile
    container_name: basic-ml-app
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped